# Generated by Django 5.1.2 on 2024-10-15 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_alter_chat_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_text', models.TextField()),
                ('message_type', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=4)),
                ('feed_back', models.TextField(blank=True, null=True)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat')),
            ],
        ),
    ]
