# Generated by Django 5.1.2 on 2024-10-16 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='chat_id',
            new_name='chat',
        ),
    ]
