# Generated by Django 5.1.2 on 2024-10-16 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_rename_chat_id_chatmessage_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
