# Generated by Django 5.1.2 on 2024-10-16 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_chatmessage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
