# Generated by Django 5.1.2 on 2024-10-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created_by',
            field=models.CharField(max_length=255),
        ),
    ]
