# Generated by Django 5.1.2 on 2024-10-15 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_requisition_chat_requisition_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='requisition_id',
            new_name='requisition',
        ),
    ]
