# Generated by Django 5.1.2 on 2024-10-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chat_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='feedback',
            field=models.TextField(default=None, null=True),
        ),
    ]
