# Generated by Django 5.1.2 on 2024-10-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requistion', '0002_rename_rfq_requisition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='created_by',
            field=models.CharField(max_length=255),
        ),
    ]
