# Generated by Django 5.1.2 on 2024-10-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requistion', '0003_alter_requisition_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='payment_terms',
            field=models.TextField(),
        ),
    ]
